/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bag` | `/bag`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/info` | `/info`; params?: Router.UnknownInputParams; } | { pathname: `/custom`; params?: Router.UnknownInputParams; } | { pathname: `/log-in`; params?: Router.UnknownInputParams; } | { pathname: `/not-login-search`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/terms-agreement`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/bag/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/bag/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/gear-detail/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/gear-edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/useless/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bag` | `/bag`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/info` | `/info`; params?: Router.UnknownOutputParams; } | { pathname: `/custom`; params?: Router.UnknownOutputParams; } | { pathname: `/log-in`; params?: Router.UnknownOutputParams; } | { pathname: `/not-login-search`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/terms-agreement`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/bag/[id]/edit`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/bag/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/gear-detail/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/gear-edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/useless/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bag${`?${string}` | `#${string}` | ''}` | `/bag${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/info${`?${string}` | `#${string}` | ''}` | `/info${`?${string}` | `#${string}` | ''}` | `/custom${`?${string}` | `#${string}` | ''}` | `/log-in${`?${string}` | `#${string}` | ''}` | `/not-login-search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/terms-agreement${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bag` | `/bag`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/info` | `/info`; params?: Router.UnknownInputParams; } | { pathname: `/custom`; params?: Router.UnknownInputParams; } | { pathname: `/log-in`; params?: Router.UnknownInputParams; } | { pathname: `/not-login-search`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/terms-agreement`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/bag/${Router.SingleRoutePart<T>}/edit${`?${string}` | `#${string}` | ''}` | `/bag/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/gear-detail/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/gear-edit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/useless/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/bag/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/bag/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/gear-detail/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/gear-edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/useless/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
